### ISSUE TITLE
java.lang.NoClassDefFoundError: scala/collection/immutable/StringOps 문제 발생

### ISSUE THREAD

**Issue by lifefeel** [koalanlp/koalanlp#25]
### 기초정보
- KoalaNLP 버전은 얼마였나요? 
2.1.3

- 어떤 프로그래밍 언어에서 문제가 생겼습니까? ([]안에 x표하여 표기해주세요)
Python 3.6

- 문제의 유형은 어떤 것인가요?
버그리포트

### 재연을 위한 정보
- 초기화 시에 문제가 생깁니다. Ubuntu 및 OS X 에서 둘다 아래와 같은 문제가 발생합니다.
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/koalanlp/proc.py", line 39, in sentences
    result += py_list(self.__api.invoke(string(paragraph)), lambda x: x)
  File "/usr/lib/python3.6/site-packages/py4j/java_gateway.py", line 1286, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/usr/lib/python3.6/site-packages/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o209.invoke.
: java.lang.NoClassDefFoundError: scala/collection/immutable/StringOps
	at org.openkoreantext.processor.tokenizer.KoreanSentenceSplitter$.<init>(KoreanSentenceSplitter.scala:30)
	at org.openkoreantext.processor.tokenizer.KoreanSentenceSplitter$.<clinit>(KoreanSentenceSplitter.scala)
	at org.openkoreantext.processor.OpenKoreanTextProcessor$.splitSentences(OpenKoreanTextProcessor.scala:144)
	at org.openkoreantext.processor.OpenKoreanTextProcessor.splitSentences(OpenKoreanTextProcessor.scala)
	at kr.bydelta.koala.okt.SentenceSplitter.sentences(proc.kt:162)
	at kr.bydelta.koala.proc.CanSplitSentence$DefaultImpls.invoke(processors.kt:63)
	at kr.bydelta.koala.okt.SentenceSplitter.invoke(proc.kt:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: scala.collection.immutable.StringOps
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more

```
- KoalaNLP를 사용한 코드 부분을 보여주세요.
```python
initialize(OKT='latest', force_download=False)
```

### 본문
매뉴얼에 있는 사전설치 항목은 모두 설치했는데 위와 같은 문제가 발생합니다. 도움을 주실 수 있나요?

**Comment by nearbydelta** [comment]
OpenKoreanText 라이브러리가 제대로 다운로드가 안 된 것 같습니다. 다음 명령으로 다시 한번 받아보시겠어요?
```python
initialize(OKT='latest', force_download=True)
```
또는 작업중인 폴더 하위에 있는 `.java` 폴더를 지우고 다시 해보시길 바랍니다.

초기화 과정 중에는 jar 파일을 다운로드하는데, 이 과정에 KeyboardInterrupt 등으로 문제가 생기면 저런 일이 생깁니다. initialize 함수가 끝날때까지 되도록 기다려주세요 (한 번만 받으면 다음에는 초기화가 빠릅니다). 이 부분 문제는 해결 방법을 생각하고 있지만, 당분간은 이렇게 쓰셔야 할 것 같습니다.

**Comment by nearbydelta** [comment]
다른 피드백이 없으셔서, 이 thread는 우선 닫겠습니다. 문제가 생기면 다시 열어주세요.
